# Generated by Django 3.2.8 on 2021-10-20 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_auto_20211017_0754'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requestedinformation',
            name='kind',
            field=models.CharField(choices=[('tel', 'phone number'), ('email', 'email'), ('password', 'password'), ('date', 'date'), ('text', 'text'), ('number', 'number'), ('url', 'website link'), ('time', 'time'), ('datetime-local', 'date and time')], max_length=150),
        ),
    ]
